In [13]:
import pandas as pd

In [ ]:
df = pd.read_csv("D:/EM_38/data/VenueLook2.csv")

In [16]:
df.shape

(3684, 10)

In [ ]:
df.head(5)

,name,bg_img_link,mark,category,rating,price,address,role,city,int_price
0,Woodapple Residency,https://cdn.venuelook.com/uploads/space_2877/1...,"Karkardooma, Delhi",banquet-halls,4.8,Rs. 699 price per plat,"Near Karkarduma Court Metro Station,\nEverythi...",NONE,delhi,699
1,Venizia Sarovar Portico,https://cdn.venuelook.com/uploads/space_1824/1...,"Model Town, Delhi",banquet-halls,4.9,Rs. 1000 price per plat,Aesthetically designed amidst the lush greenry...,Royal Hall,delhi,1000
2,Luxera Hotels Banquets Convention & Catering,https://cdn.venuelook.com/uploads/space_25396/...,"Mg Road, Delhi",banquet-halls,4.6,Rs. 1800 price per plat,"Near Ambience Mall Mall,\nLuxera Hotels Banque...",Iris Hall Ground,delhi,1800
3,Tivoli Grand,https://cdn.venuelook.com/uploads/space_165/16...,"Gt Karnal Road, Delhi",banquet-halls,4.7,Rs. 1800 price per plat,"Near TDI Mall Kundli Mall,\nThe Royal Ballroom...",The Royal Ballroom,delhi,1800
4,Calista Resort Delhi,https://cdn.venuelook.com/uploads/space_9254/1...,"Kapashera, Delhi",banquet-halls,4.8,Rs. 2500 price per plat,"Near Ambience Mall Mall,\nCalista Resort, Kapa...",The Ball Room,delhi,2500

:

In [21]:
df.info

<bound method DataFrame.info of                                               name  \
0                              Woodapple Residency
1                          Venizia Sarovar Portico
2     Luxera Hotels Banquets Convention & Catering
3                                     Tivoli Grand
4                             Calista Resort Delhi
...                                            ...
3679                            Event Corporations
3680                                  Giggle Event
3681                                        Regale
3682                          Ifd Wedding Planners
3683                                The Bliss Wish

                                            bg_img_link  \
0     https://cdn.venuelook.com/uploads/space_2877/1...
1     https://cdn.venuelook.com/uploads/space_1824/1...
2     https://cdn.venuelook.com/uploads/space_25396/...
3     https://cdn.venuelook.com/uploads/space_165/16...
4     https://cdn.venuelook.com/uploads/space_9254/1...
...                                                 ...
3679  https://cdn.venuelook.com/uploads/vendoralbums...
3680  https://cdn.venuelook.com/uploads/vendoralbums...
3681  https://cdn.venuelook.com/uploads/vendoralbums...
3682  https://cdn.venuelook.com/uploads/vendoralbums...
3683  https://cdn.venuelook.com/uploads/vendoralbums...

                                              mark        category  rating  \
0                               Karkardooma, Delhi   banquet-halls     4.8
1                                Model Town, Delhi   banquet-halls     4.9
2                                   Mg Road, Delhi   banquet-halls     4.6
3                            Gt Karnal Road, Delhi   banquet-halls     4.7
4                                 Kapashera, Delhi   banquet-halls     4.8
...                                            ...             ...     ...
3679  Sector 132 near Jaypee Hospital Noida, Noida  event-planners     3.0
3680                              sector 25, Noida  event-planners     3.0
3681                   Noida, Uttar Pradesh, Noida  event-planners     3.0
3682                        Noida Extension, Noida  event-planners     3.0
3683                              Sector 12, Noida  event-planners     3.0

                        price  \
0      Rs. 699 price per plat
1     Rs. 1000 price per plat
2     Rs. 1800 price per plat
3     Rs. 1800 price per plat
4     Rs. 2500 price per plat
...                       ...
3679  Starting Price:  250000
3680  Starting Price:  250000
3681  Starting Price:  600000
3682  Starting Price:  400000
3683  Starting Price:  250000

                                                address                role  \
0     Near Karkarduma Court Metro Station,\nEverythi...                NONE
1     Aesthetically designed amidst the lush greenry...          Royal Hall
2     Near Ambience Mall Mall,\nLuxera Hotels Banque...    Iris Hall Ground
3     Near TDI Mall Kundli Mall,\nThe Royal Ballroom...  The Royal Ballroom
4     Near Ambience Mall Mall,\nCalista Resort, Kapa...       The Ball Room
...                                                 ...                 ...
3679       Sector 132 near Jaypee Hospital Noida, Noida      event-planners
3680                                   sector 25, Noida      event-planners
3681                        Noida, Uttar Pradesh, Noida      event-planners
3682                             Noida Extension, Noida      event-planners
3683                                   Sector 12, Noida      event-planners

               city  int_price
0             delhi        699
1             delhi       1000
2             delhi       1800
3             delhi       1800
4             delhi       2500
...             ...        ...
3679  greater-noida     250000
3680  greater-noida     250000
3681  greater-noida     600000
3682  greater-noida     400000
3683  greater-noida     250000

[3684 rows x 10 columns]>

In [18]:
df.describe().round()

       rating  int_price
count  3684.0     3684.0
mean      3.0    18410.0
std       1.0    61496.0
min       0.0      199.0
25%       2.0      799.0
50%       3.0     1400.0
75%       4.0     2500.0
max       5.0   650000.0

In [19]:
df.isnull().sum()

name           0
bg_img_link    0
mark           0
category       0
rating         0
price          0
address        0
role           0
city           0
int_price      0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("D:/EM_38/data/Venue_master.csv", encoding="latin1")  # load dataset
print("Original shape:", df.shape)
print(df["Listing_type"].unique())

Original shape: (3684, 10)
['banquet-halls' 'photographers' 'makeup-artists' 'decorators' 'dj'
 'event-planners']

In [2]:
import pandas as pd
df = pd.read_csv("D:/EM_38/data/vendors_clean.csv")
df.columns.tolist()

['vendor_id',
 'Name',
 'Image_link',
 'Location',
 'Listing_type',
 'Rating',
 'Price',
 'Description',
 'Venue_space_type',
 'City',
 'Initial_price']